import type { Archetype, Solution } from '../src/data/solutions';
import {
  CLUSTERS,
  orderSolutions,
  PINNED_SLUG,
  RATING_LABELS,
} from '../src/data/solutions';
import { escapeMdx } from './mdx';
import { TITLE_MAX } from './seoMetadata';

/**
 * One page per benchmark solution, read against SOAT: the `/benchmark`
 * dataset rendered as static prose a search engine or an agent can quote. The
 * interactive comparator filters on the client, so its per-capability notes
 * and sources are not in its HTML; these pages are where each one is stated
 * and linked.
 */

const ARCHETYPE_PHRASES: Record<Archetype, string> = {
  'managed-platform': 'a managed agent platform',
  framework: 'an agent framework',
  infrastructure: 'agent infrastructure',
};

const nativeClusters = (solution: Solution) => {
  return CLUSTERS.filter((cluster) => {
    return solution.capabilities[cluster.id].rating === 'native';
  });
};

const deploymentText = (solution: Solution): string => {
  return solution.deployment.join(' or ');
};

const labels = (clusters: typeof CLUSTERS): string => {
  return clusters
    .map((cluster) => {
      return cluster.label.toLowerCase();
    })
    .join(', ');
};

/** Room left in a doc title once the theme appends ` | SOAT`. */
const TITLE_ROOM = TITLE_MAX - ' | SOAT'.length;

export const compareTitle = (args: { solution: Solution }): string => {
  const title = `${args.solution.name} vs SOAT: Feature Comparison`;
  return title.length <= TITLE_ROOM ? title : `${args.solution.name} vs SOAT`;
};

export const compareDescription = (args: {
  solution: Solution;
  baseline: Solution;
}): string => {
  const { solution, baseline } = args;
  return `${solution.name} and SOAT compared on ${CLUSTERS.length} agent capabilities, ${nativeClusters(solution).length} vs ${nativeClusters(baseline).length} native, each rating linked to its source.`;
};

const rating = (args: { solution: Solution; clusterId: string }) => {
  const capability = args.solution.capabilities[args.clusterId];
  const source = capability.evidence
    ? ` ([source](${capability.evidence}))`
    : '';
  return `- **${args.solution.name}: ${RATING_LABELS[capability.rating]}.** ${escapeMdx(capability.note)}${source}`;
};

const onlyNativeIn = (args: { solution: Solution; other: Solution }) => {
  return nativeClusters(args.solution).filter((cluster) => {
    return args.other.capabilities[cluster.id].rating !== 'native';
  });
};

const leadSentence = (args: { solution: Solution; other: Solution }) => {
  const clusters = onlyNativeIn(args);
  return clusters.length > 0
    ? `- **${args.solution.name}** is native where ${args.other.name} is not: ${labels(clusters)}.`
    : `- **${args.solution.name}** has no native capability that ${args.other.name} lacks.`;
};

export const renderComparePage = (args: {
  solution: Solution;
  baseline: Solution;
}): string => {
  const { solution, baseline } = args;
  const answer = `${solution.name} is ${ARCHETYPE_PHRASES[solution.archetype]} (${solution.license}, ${deploymentText(solution)}). SOAT is ${ARCHETYPE_PHRASES[baseline.archetype]} (${baseline.license}, ${deploymentText(baseline)}). Of the ${CLUSTERS.length} capabilities the [benchmark](/benchmark) tracks, ${solution.name} covers ${nativeClusters(solution).length} natively and SOAT ${nativeClusters(baseline).length}.`;

  const glance = [
    `| | ${solution.name} | SOAT |`,
    '| --- | --- | --- |',
    `| Type | ${ARCHETYPE_PHRASES[solution.archetype]} | ${ARCHETYPE_PHRASES[baseline.archetype]} |`,
    `| License | ${solution.license} | ${baseline.license} |`,
    `| Deployment | ${deploymentText(solution)} | ${deploymentText(baseline)} |`,
    `| Native capabilities | ${nativeClusters(solution).length} of ${CLUSTERS.length} | ${nativeClusters(baseline).length} of ${CLUSTERS.length} |`,
    `| Last verified | ${solution.last_verified} | ${baseline.last_verified} |`,
  ].join('\n');

  const capabilities = CLUSTERS.map((cluster) => {
    return [
      `### ${cluster.label}`,
      `_${cluster.description}_`,
      [
        rating({ solution, clusterId: cluster.id }),
        rating({ solution: baseline, clusterId: cluster.id }),
      ].join('\n'),
    ].join('\n\n');
  }).join('\n\n');

  return `---
title: "${compareTitle({ solution })}"
sidebar_label: "${solution.name}"
description: "${compareDescription({ solution, baseline })}"
---

{/* This page is generated by packages/website/scripts/generateComparePages.ts from src/data/solutions — do not edit by hand. */}

# SOAT vs ${solution.name}

${answer}

## At a glance

${glance}

## Where each one leads

${leadSentence({ solution, other: baseline })}
${leadSentence({ solution: baseline, other: solution })}

## What ${solution.name} is

${escapeMdx(solution.summary)} [${solution.name} documentation](${solution.website}).

## Capability by capability

${capabilities}

## How this is rated

Each rating comes from the public documentation linked beside it: **Native** is built in, **Via plugin** needs an add-on, **Partial** covers part of the capability, **Absent** is not offered. Every solution side by side is on the [benchmark](/benchmark). A rating that is out of date is a bug: [open an issue](https://github.com/ttoss/soat/issues).
`;
};

export const renderCompareIndex = (args: {
  solutions: Solution[];
  baseline: Solution;
}): string => {
  const rows = orderSolutions(args.solutions)
    .filter((solution) => {
      return solution.slug !== PINNED_SLUG;
    })
    .map((solution) => {
      return `| [${solution.name}](./${solution.slug}.md) | ${ARCHETYPE_PHRASES[solution.archetype]} | ${deploymentText(solution)} | ${nativeClusters(solution).length} of ${CLUSTERS.length} |`;
    });

  return `---
title: "AI Agent Platforms Compared with SOAT"
slug: /compare
sidebar_label: "Overview"
sidebar_position: 0
description: "${rows.length} AI agent platforms, frameworks and infrastructure projects compared with SOAT, capability by capability, each rating linked to its source."
---

{/* This page is generated by packages/website/scripts/generateComparePages.ts from src/data/solutions — do not edit by hand. */}

# Compare SOAT

Each page reads one solution against SOAT across the ${CLUSTERS.length} capabilities of the [benchmark](/benchmark), with the documentation behind every rating. SOAT covers ${nativeClusters(args.baseline).length} of them natively.

| Solution | Type | Deployment | Native capabilities |
| --- | --- | --- | --- |
${rows.join('\n')}
`;
};
