/**
 * Generates packages/website/docs/error-codes.md from the server's error
 * registry (`packages/server/src/errors/`).
 *
 * The page is the human-readable twin of `/errors.json`, and the target of the
 * `docs_url` every error response carries: a caller that gets
 * `RESOURCE_NOT_FOUND` can follow `docs_url` straight to the anchor that
 * explains it. That link only resolves because this page exists and its
 * headings are the codes themselves — so the page is generated, never written
 * by hand, and a code added to the registry documents itself.
 *
 * Run with: pnpm tsx scripts/generateErrorCodesPage.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as url from 'node:url';

import { ERROR_CODES } from '../../server/src/errors/codes';
import {
  docsUrlFor,
  resolutionFor,
  STATUS_RESOLUTIONS,
} from '../../server/src/errors/resolutions';
import { escapeMdx } from './mdx';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

const OUTPUT_FILE = path.resolve(__dirname, '../docs/error-codes.md');

type ErrorCode = keyof typeof ERROR_CODES;

const sortedCodes = (): ErrorCode[] => {
  return (Object.keys(ERROR_CODES) as ErrorCode[]).sort();
};

/** The anchor `docs_url` points at, which Docusaurus derives from the heading. */
export const anchorFor = (args: { code: string }): string => {
  return args.code.toLowerCase();
};

const escapeCell = (text: string): string => {
  return escapeMdx(text).replace(/\|/g, '\\|');
};

export const renderErrorCodesPage = (): string => {
  const codes = sortedCodes();

  const summaryRows = codes
    .map((code) => {
      return `| [\`${code}\`](#${anchorFor({ code })}) | ${ERROR_CODES[code].httpStatus} | ${escapeCell(ERROR_CODES[code].description)} |`;
    })
    .join('\n');

  const statusRows = Object.keys(STATUS_RESOLUTIONS)
    .map(Number)
    .sort((a, b) => {
      return a - b;
    })
    .map((status) => {
      return `| ${status} | ${escapeCell(STATUS_RESOLUTIONS[status])} |`;
    })
    .join('\n');

  const sections = codes
    .map((code) => {
      return [
        `### ${code}`,
        '',
        `**HTTP ${ERROR_CODES[code].httpStatus}** — ${escapeMdx(ERROR_CODES[code].description)}`,
        '',
        `**What to do:** ${escapeMdx(resolutionFor({ code }))}`,
        '',
        `Reached by \`docs_url\`: \`${docsUrlFor({ code })}\``,
      ].join('\n');
    })
    .join('\n\n');

  return `---
description: 'Every error code the SOAT API can return, with its HTTP status and what to do about it.'
---

{/* Generated by scripts/generateErrorCodesPage.ts — do not edit by hand. */}

# Error Codes

Every failing request answers with the same body, whatever went wrong:

\`\`\`json
{
  "error": {
    "code": "RESOURCE_NOT_FOUND",
    "message": "Project 'proj_abc123' not found.",
    "hint": "Check the id, and check that the credential can see the project that owns the resource…",
    "docs_url": "https://soat.ttoss.dev/docs/error-codes#resource_not_found",
    "meta": { "id": "proj_abc123" }
  }
}
\`\`\`

- \`code\` is stable — branch on it, never on \`message\`.
- \`message\` describes this occurrence and may name ids or fields.
- \`hint\` says what to do about it, so a caller meeting a code for the first
  time can act without leaving the response.
- \`docs_url\` addresses the section for that code on this page.
- \`meta\` is present only for codes that carry structured context.

The same catalog is published as JSON at [/errors.json](/errors.json) and as the
\`x-error-codes\` extension of [/openapi.json](/openapi.json). Both are generated
from the server source, so a client can branch on codes without scraping this
page.

## Hints by status class

A code without a hint of its own inherits the one for its HTTP status, so every
code answers with something actionable:

| Status | Default hint |
| --- | --- |
${statusRows}

## All codes

| Code | Status | Meaning |
| --- | --- | --- |
${summaryRows}

## Reference

${sections}
`;
};

fs.writeFileSync(OUTPUT_FILE, renderErrorCodesPage(), 'utf-8');

process.stdout.write(
  `[error-codes] wrote ${sortedCodes().length} codes to ${path.relative(process.cwd(), OUTPUT_FILE)}\n`
);
