/**
 * Generates packages/website/docs/webhook-events.md from the event registry in
 * packages/server/src/lib/soatEvents.ts.
 *
 * The list of events the platform emits used to exist only as string literals
 * scattered across ~38 emit sites, which meant the documentation was whatever a
 * human last remembered to write down. Registering an event and documenting it
 * are now the same edit.
 *
 * Run with: pnpm tsx scripts/generateWebhookEventsPage.ts
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import * as url from 'node:url';

import { SOAT_EVENTS } from '../../server/src/lib/soatEvents';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));

const OUTPUT_FILE = path.resolve(__dirname, '../docs/webhook-events.md');

const escapeCell = (value: string): string => {
  return value.replace(/\|/g, '\\|');
};

const renderTable = (events: Readonly<Record<string, string>>): string => {
  const rows = Object.entries(events).map(([name, description]) => {
    return `| \`${name}\` | ${escapeCell(description)} |`;
  });

  return ['| Event | Description |', '| --- | --- |', ...rows].join('\n');
};

const renderPage = (): string => {
  const sections = Object.entries(SOAT_EVENTS)
    .sort(([a], [b]) => {
      return a.localeCompare(b);
    })
    .map(([resourceType, events]) => {
      return `## \`${resourceType}\`\n\n${renderTable(events)}`;
    });

  const total = Object.values(SOAT_EVENTS).reduce((sum, events) => {
    return sum + Object.keys(events).length;
  }, 0);

  return `---
description: "Every event SOAT emits, the resource type each belongs to, and what it means."
---

{/* This page is generated by packages/website/scripts/generateWebhookEventsPage.ts — do not edit by hand. */}

# Webhook Events

The ${total} events SOAT emits, grouped by the \`resource_type\` each carries. A [webhook](./modules/webhooks.md) subscribes to them by exact name, by \`<prefix>.*\`, or to all of them with \`*\`.

Each event arrives as the envelope described in [Webhooks → Event Payload](./modules/webhooks.md#event-payload): the name below is the \`event\` field and the \`X-Soat-Event\` header, the heading above each table is the \`resource_type\` field, and \`data\` carries the resource in the same shape the REST API returns it.

An orchestration [\`emit_event\` node](./modules/orchestrations.md) also emits events, under whatever name the template author chose. Those are not listed here — they are yours, not SOAT's — and they carry \`resource_type: orchestration_run\`.

${sections.join('\n\n')}
`;
};

fs.writeFileSync(OUTPUT_FILE, renderPage());

// eslint-disable-next-line no-console
console.log(`Generated ${path.relative(process.cwd(), OUTPUT_FILE)}`);
