import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Navbar structure: Docs · Tutorials · Reference (see README.md).
 *
 * - docsSidebar — learning-oriented content: getting started, client surface
 *   setup guides, the grouped Platform (module) pages, and self-hosting.
 * - tutorialSidebar — end-to-end walkthroughs, grouped by theme.
 * - referenceSidebar — generated / lookup material: REST API, SDK services,
 *   CLI commands, MCP tools, formation types, expressions, permissions.
 *
 * Module and tutorial files are grouped here explicitly (not autogenerated)
 * so the sidebar mirrors the mental model taught in introduction.md and
 * getting-started/concepts.md. When adding a new module or tutorial page,
 * add its doc id to the matching category below.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'introduction',
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/quick-start' },
      collapsed: false,
      items: [
        'getting-started/quick-start',
        'getting-started/concepts',
        'getting-started/choosing-a-client',
      ],
    },
    {
      type: 'category',
      label: 'Client Surfaces',
      items: [
        {
          type: 'category',
          label: 'SDK',
          link: { type: 'doc', id: 'sdk/introduction' },
          items: ['sdk/introduction', 'sdk/usage'],
        },
        {
          type: 'category',
          label: 'CLI',
          link: { type: 'doc', id: 'cli/introduction' },
          items: ['cli/introduction', 'cli/usage'],
        },
        {
          type: 'category',
          label: 'MCP',
          link: { type: 'doc', id: 'mcp/introduction' },
          items: ['mcp/introduction', 'mcp/connecting'],
        },
      ],
    },
    {
      type: 'category',
      label: 'Platform',
      link: { type: 'doc', id: 'modules/index' },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Identity & Access',
          items: [
            'modules/users',
            'modules/projects',
            'modules/iam',
            'modules/policies',
            'modules/api-keys',
            'modules/oauth',
          ],
        },
        {
          type: 'category',
          label: 'Storage & Retrieval',
          items: [
            'modules/files',
            'modules/documents',
            'modules/embeddings',
            'modules/ingestion-rules',
            'modules/knowledge',
            'modules/memories',
          ],
        },
        {
          type: 'category',
          label: 'Agents & Conversations',
          items: [
            'modules/ai-providers',
            'modules/agents',
            'modules/tools',
            'modules/sessions',
            'modules/conversations',
            'modules/chats',
            'modules/actors',
            'modules/generations',
          ],
        },
        {
          type: 'category',
          label: 'Orchestration & Automation',
          items: [
            'modules/orchestrations',
            'modules/discussions',
            'modules/triggers',
            'modules/webhooks',
            'modules/approvals',
          ],
        },
        {
          type: 'category',
          label: 'Declarative Deployment',
          items: ['modules/formations'],
        },
        {
          type: 'category',
          label: 'Operations',
          items: [
            'modules/traces',
            'modules/usage',
            'modules/secrets',
            'modules/docs',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Self-Hosting & Production',
      link: { type: 'doc', id: 'getting-started/advanced-config' },
      items: ['getting-started/advanced-config'],
    },
  ],

  tutorialSidebar: [
    'tutorials/index',
    {
      type: 'category',
      label: 'Basics',
      collapsed: false,
      items: [
        'tutorials/permissions',
        'tutorials/chat-with-llm',
        'tutorials/connect-third-party-llms',
      ],
    },
    {
      type: 'category',
      label: 'Agents',
      items: [
        'tutorials/agent-soat-tools',
        'tutorials/memories-agent',
        'tutorials/debug-session-generation-trace-history',
      ],
    },
    {
      type: 'category',
      label: 'Knowledge & RAG',
      items: [
        'tutorials/embeddings',
        'tutorials/agent-with-pdfs',
        'tutorials/ingest-images-and-audio',
      ],
    },
    {
      type: 'category',
      label: 'Orchestration & Multi-Agent',
      items: [
        'tutorials/orchestrate-a-sonnet',
        'tutorials/multi-agent-orchestration',
        'tutorials/conditional-orchestration',
        'tutorials/orchestration-control-flow',
        'tutorials/approval-gate',
        'tutorials/create-an-agent-squad',
        'tutorials/review-panel-discussion',
      ],
    },
    {
      type: 'category',
      label: 'Automation & Deployment',
      items: [
        'tutorials/formations',
        'tutorials/automate-a-flow-with-triggers',
      ],
    },
  ],

  // Generated / lookup-oriented material. Most doc ids below only exist after
  // `pnpm generate-all` runs (they are gitignored build outputs).
  referenceSidebar: [
    {
      type: 'category',
      label: 'REST API',
      link: { type: 'doc', id: 'api/index' },
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
    {
      type: 'category',
      label: 'SDK Services',
      link: { type: 'doc', id: 'sdk/services' },
      items: [{ type: 'autogenerated', dirName: 'sdk/services' }],
    },
    {
      type: 'category',
      label: 'CLI Commands',
      link: { type: 'doc', id: 'cli/commands' },
      items: [{ type: 'autogenerated', dirName: 'cli/commands' }],
    },
    {
      type: 'category',
      label: 'MCP Tools',
      link: { type: 'doc', id: 'mcp/tools' },
      items: [{ type: 'autogenerated', dirName: 'mcp/tools' }],
    },
    {
      type: 'category',
      label: 'Formation Types',
      link: { type: 'doc', id: 'formations-types/index' },
      items: [{ type: 'autogenerated', dirName: 'formations-types' }],
    },
    {
      type: 'doc',
      id: 'advanced/expressions-and-templating',
      label: 'Expressions & Templating',
    },
    'permissions',
    'openapi-specs',
  ],
};

export default sidebars;
