import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

import documentsSidebar from './docs/api/documents/sidebar';
import filesSidebar from './docs/api/files/sidebar';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'intro',
    'getting-started',
    {
      type: 'category',
      label: 'Tutorials',
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'Modules',
      items: ['modules/files'],
    },
  ],

  // API sidebar - combines the generated OpenAPI sidebars
  apiSidebar: [
    {
      type: 'category',
      label: 'Documents API',
      items: documentsSidebar,
    },
    {
      type: 'category',
      label: 'Files API',
      items: filesSidebar,
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
