import { Router } from '@ttoss/http-server';

import { actorsRouter } from './actors';
import { actorTagsRouter } from './actorTags';
import { agentsRouter } from './agents';
import { aiProvidersRouter } from './aiProviders';
import { apiKeysRouter } from './apiKeys';
import { approvalsRouter } from './approvals';
import { chatsRouter } from './chats';
import { conversationsRouter } from './conversations';
import { discussionsRouter } from './discussions';
import { documentsRouter } from './documents';
import { embeddingsRouter } from './embeddings';
import { filesRouter } from './files';
import { formationsRouter } from './formations';
import { generationsRouter } from './generations';
import { guardrailsRouter } from './guardrails';
import { ingestionRulesRouter } from './ingestionRules';
import { knowledgeRouter } from './knowledge';
import { memoriesRouter } from './memories';
import { memoryEntriesRouter } from './memoryEntries';
import { oauthRouter } from './oauth';
import { openapiRouter } from './openapi';
import { orchestrationsRouter } from './orchestrations';
import { policiesRouter } from './policies';
import { projectsRouter } from './projects';
import { secretsRouter } from './secrets';
import { sessionsRouter } from './sessions';
import { tasksRouter } from './tasks';
import { toolsRouter } from './tools';
import { tracesRouter } from './traces';
import { triggersRouter } from './triggers';
import { usageRouter } from './usage';
import { usersRouter } from './users';
import { webhooksRouter } from './webhooks';
import { workflowsRouter } from './workflows';

const v1Router = new Router();

v1Router.use(formationsRouter.routes());
v1Router.use(generationsRouter.routes());
v1Router.use(guardrailsRouter.routes());
v1Router.use(agentsRouter.routes());
v1Router.use(sessionsRouter.routes());
v1Router.use(chatsRouter.routes());
v1Router.use(actorsRouter.routes());
v1Router.use(actorTagsRouter.routes());
v1Router.use(aiProvidersRouter.routes());
v1Router.use(apiKeysRouter.routes());
v1Router.use(approvalsRouter.routes());
v1Router.use(memoriesRouter.routes());
v1Router.use(memoryEntriesRouter.routes());
v1Router.use(oauthRouter.routes());
v1Router.use(policiesRouter.routes());
v1Router.use(conversationsRouter.routes());
v1Router.use(discussionsRouter.routes());
v1Router.use(documentsRouter.routes());
v1Router.use(ingestionRulesRouter.routes());
v1Router.use(embeddingsRouter.routes());
v1Router.use(filesRouter.routes());
v1Router.use(knowledgeRouter.routes());
v1Router.use(projectsRouter.routes());
v1Router.use(secretsRouter.routes());
v1Router.use(orchestrationsRouter.routes());
v1Router.use(workflowsRouter.routes());
v1Router.use(tasksRouter.routes());
v1Router.use(toolsRouter.routes());
v1Router.use(tracesRouter.routes());
v1Router.use(triggersRouter.routes());
v1Router.use(usageRouter.routes());
v1Router.use(usersRouter.routes());
v1Router.use(webhooksRouter.routes());
v1Router.use(openapiRouter.routes());

export { v1Router };
