openapi: 3.0.3
info:
  title: SOAT Documents API
  version: 1.0.0
  description: API for managing documents with embeddings support
  contact:
    name: SOAT Team
    url: https://github.com/ttoss/soat
servers:
  - url: http://0.0.0.0:5047/api/v1
    description: Development server
paths:
  /documents:
    get:
      tags:
        - Documents
      summary: List all documents
      description: Returns a list of all documents stored in the system
      operationId: listDocuments
      responses:
        '200':
          description: Documents list returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  documents:
                    type: array
                    items:
                      $ref: '#/components/schemas/DocumentRecord'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - Documents
      summary: Create a new document
      description: Creates a new document with optional embedding generation. The document content is saved as a markdown file.
      operationId: createDocument
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                  description: Document content in markdown format
                  example: '# My Document\n\nThis is the content of my document.'
                title:
                  type: string
                  description: Document title
                  example: 'My Document'
                metadata:
                  type: object
                  additionalProperties: true
                  description: Additional metadata for the document
                  example:
                    author: 'John Doe'
                    tags: ['example', 'documentation']
                generateEmbedding:
                  type: boolean
                  description: Whether to generate embedding for the document (default true if embedding config is available)
                  default: true
      responses:
        '201':
          description: Document created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  document:
                    $ref: '#/components/schemas/DocumentResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /documents/search:
    get:
      tags:
        - Documents
      summary: Search documents by similarity
      description: Searches for documents similar to the query using vector similarity. Requires embedding configuration (EMBEDDINGS_OLLAMA_MODEL or EMBEDDINGS_OPENAI_KEY).
      operationId: searchDocuments
      parameters:
        - name: query
          in: query
          required: true
          description: Search query text
          schema:
            type: string
          example: 'machine learning concepts'
        - name: limit
          in: query
          required: false
          description: Maximum number of results to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
          example: 5
        - name: threshold
          in: query
          required: false
          description: Minimum similarity threshold (0-1)
          schema:
            type: number
            minimum: 0
            maximum: 1
          example: 0.7
      responses:
        '200':
          description: Search results returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  documents:
                    type: array
                    items:
                      $ref: '#/components/schemas/DocumentWithContent'
        '400':
          description: Bad request (query missing or embedding not configured)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /documents/{id}:
    get:
      tags:
        - Documents
      summary: Get a document by ID
      description: Returns a document with its content
      operationId: getDocument
      parameters:
        - name: id
          in: path
          required: true
          description: Document ID
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      responses:
        '200':
          description: Document returned successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  document:
                    $ref: '#/components/schemas/DocumentWithContent'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Documents
      summary: Update a document
      description: Updates an existing document. If content is changed, a new file is created and the old one is deleted. Embedding can be regenerated.
      operationId: updateDocument
      parameters:
        - name: id
          in: path
          required: true
          description: Document ID
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: New document content in markdown format
                  example: '# Updated Document\n\nThis is the updated content.'
                title:
                  type: string
                  description: New document title
                  example: 'Updated Title'
                metadata:
                  type: object
                  additionalProperties: true
                  description: New metadata for the document
                  example:
                    author: 'Jane Doe'
                    version: 2
                regenerateEmbedding:
                  type: boolean
                  description: Whether to regenerate embedding when content changes (default true)
                  default: true
      responses:
        '200':
          description: Document updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  document:
                    $ref: '#/components/schemas/DocumentWithContent'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Documents
      summary: Delete a document
      description: Deletes a document and its associated file
      operationId: deleteDocument
      parameters:
        - name: id
          in: path
          required: true
          description: Document ID
          schema:
            type: string
            format: uuid
          example: '550e8400-e29b-41d4-a716-446655440000'
      responses:
        '200':
          description: Document deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    DocumentRecord:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Document ID
          example: '550e8400-e29b-41d4-a716-446655440000'
        title:
          type: string
          description: Document title
          example: 'My Document'
        fileId:
          type: string
          format: uuid
          description: Associated file ID
          example: '660e8400-e29b-41d4-a716-446655440001'
        embeddingModel:
          type: string
          description: Model used to generate embedding
          example: 'nomic-embed-text'
        embeddingProvider:
          type: string
          description: Provider used for embedding
          enum: ['ollama', 'openai']
          example: 'ollama'
        hasEmbedding:
          type: boolean
          description: Whether the document has an embedding
          example: true
        metadata:
          type: object
          additionalProperties: true
          description: Document metadata
          example:
            author: 'John Doe'
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: '2026-01-07T10:00:00Z'
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: '2026-01-07T10:00:00Z'
    DocumentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Document ID
          example: '550e8400-e29b-41d4-a716-446655440000'
        title:
          type: string
          description: Document title
          example: 'My Document'
        fileId:
          type: string
          format: uuid
          description: Associated file ID
          example: '660e8400-e29b-41d4-a716-446655440001'
        embeddingModel:
          type: string
          description: Model used to generate embedding
          example: 'nomic-embed-text'
        embeddingProvider:
          type: string
          description: Provider used for embedding
          enum: ['ollama', 'openai']
          example: 'ollama'
        hasEmbedding:
          type: boolean
          description: Whether the document has an embedding
          example: true
        metadata:
          type: object
          additionalProperties: true
          description: Document metadata
          example:
            author: 'John Doe'
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: '2026-01-07T10:00:00Z'
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: '2026-01-07T10:00:00Z'
    DocumentWithContent:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Document ID
          example: '550e8400-e29b-41d4-a716-446655440000'
        title:
          type: string
          description: Document title
          example: 'My Document'
        fileId:
          type: string
          format: uuid
          description: Associated file ID
          example: '660e8400-e29b-41d4-a716-446655440001'
        content:
          type: string
          description: Document content
          example: '# My Document\n\nThis is the content of my document.'
        embeddingModel:
          type: string
          description: Model used to generate embedding
          example: 'nomic-embed-text'
        embeddingProvider:
          type: string
          description: Provider used for embedding
          enum: ['ollama', 'openai']
          example: 'ollama'
        metadata:
          type: object
          additionalProperties: true
          description: Document metadata
          example:
            author: 'John Doe'
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          example: '2026-01-07T10:00:00Z'
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          example: '2026-01-07T10:00:00Z'
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: string
          description: Error message
          example: 'An error occurred'
